# Generated by Django 4.2.4 on 2023-08-05 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('contract_terms', models.TextField()),
                ('is_signed', models.BooleanField(default=False)),
                ('employee_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification.employeerequest')),
            ],
        ),
    ]
