# Generated by Django 4.2.4 on 2023-08-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0005_bondagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondagreement',
            name='company_representative_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bondagreement',
            name='company_representative_signature',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bondagreement',
            name='company_representative_signature_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bondagreement',
            name='company_representative_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bondagreement',
            name='employee_signature',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bondagreement',
            name='employee_signature_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
