# Generated by Django 4.2.4 on 2023-08-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0006_bondagreement_company_representative_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondagreement',
            name='company_representative_name',
        ),
        migrations.RemoveField(
            model_name='bondagreement',
            name='company_representative_signature',
        ),
        migrations.RemoveField(
            model_name='bondagreement',
            name='company_representative_signature_date',
        ),
        migrations.RemoveField(
            model_name='bondagreement',
            name='company_representative_title',
        ),
        migrations.RemoveField(
            model_name='bondagreement',
            name='is_signed',
        ),
    ]
