# Generated by Django 4.2.4 on 2023-08-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0007_remove_bondagreement_company_representative_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondagreement',
            name='employee_request',
        ),
        migrations.RemoveField(
            model_name='bondagreement',
            name='employee_signature',
        ),
        migrations.RemoveField(
            model_name='bondagreement',
            name='employee_signature_date',
        ),
        migrations.AddField(
            model_name='bondagreement',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
    ]
