# Generated by Django 4.2.4 on 2023-08-06 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0008_remove_bondagreement_employee_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondagreement',
            name='employee_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='certification.employeerequest'),
        ),
    ]
